name: CI and Deploy

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    client-tests:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 'lts/*'

            - name: Install client dependencies
              run: cd client && npm install

            - name: Run client tests
              run: cd client && npm test -- --testPathPattern=App.test.js

    server-tests:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 'lts/*'

            - name: Install server dependencies
              run: cd server && npm install

            - name: Run server tests
              run: cd server && timeout 5m npm test -- --testPathPattern=server.test.js --detectOpenHandles

    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Create SSH key
              run: |
                mkdir -p ~/.ssh
                echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/metadata-fetcher-server.pem
                chmod 400 ~/.ssh/metadata-fetcher-server.pem

            - name: Deploy to EC2
              run: |
                ssh -o StrictHostKeyChecking=no -i ~/.ssh/metadata-fetcher-server.pem ubuntu@ec2-54-166-223-59.compute-1.amazonaws.com << 'EOF'
                  cd /home/ubuntu/metadata-fetcher/server
                  git pull origin main
                  pm2 list
                  pm2 delete server || true
                  pm2 start server.js --name server
                EOF